crowdsec_trusted_ips:
    - ENC[AES256_GCM,data:r4gv2xnbyVBDElEygfHE,iv:iQXq1pwGJH+jsvW9XXFSmJB2r1knSfLT+iovFYeACNQ=,tag:bfvdcMm/lWG/ek3jSUIciA==,type:str]
    - ENC[AES256_GCM,data:mBqCL+drEvnzhJxY,iv:s0/A5AIVbUvE94bUGIzY2RPc3nHX8/utc37ThmognMQ=,tag:6SMnXAPvYOrX7nnXfdBw8w==,type:str]
netdata_discord_alarm_webhook_url: ENC[AES256_GCM,data:ep1wpundbNRF5alQs0vIA0jw9Qz7/td3GuAcSg7XnuBWtTpXgCw9rG5dsZfqFou1E//F/IcOnc6Hu6FcyAO6Qpo9+dQsvEJW5ymd97d6CfqFjUTU57xnnOrHVN2W0a7njSk8CgdZC/qytdkti+ScBgQtRACkCpp7Rg==,iv:uhB3k/1A1bERewEuQpKhEebzbkUL/+exNXcgB22CKJA=,tag:PT9/qqsoCUoA26pcdB2FNg==,type:str]
forgejo_runner_token: ENC[AES256_GCM,data:E/+WNNLPACOtrVYxiCDURzh04h2KUwKWQ3uV5uPRB9zZZcp3MbwFmA==,iv:nc9BuLxZfV0dBoZOhqSPPKCpghDOrBkwfyN6ysmbs5Q=,tag:SgEtCNx9IWq/fSghX3qMXA==,type:str]
restic_ssh_hostname: ENC[AES256_GCM,data:3L9jlo8nmze43JEochpk94ApGFN++5OhH2E=,iv:HcwNOgFszUeC9Q+rtCWqWh5VWiqAuyp7l1v7DVdOKCo=,tag:Jnuxsa6Zuz+WpYoEq3qhyA==,type:str]
restic_ssh_username: ENC[AES256_GCM,data:fe0AaYZ6wA==,iv:xhcLPZOziYT9qShIPmmTaJn1kCVcZBv4nlBILp6xdKU=,tag:2P9EIbJRZKVhYnLZYNdhEw==,type:str]
restic_ssh_password: ENC[AES256_GCM,data:UGo5smej4SwMxwBDmAzx,iv:zvdlOyO6VORpwX4SygU9KiX3rjplKWX/Nlno4iQcSzE=,tag:uH2qwlCsFlO3RZhrqczaUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRW13aVU5WTlrWkt2aFIx
            VWF0Mmp1aThyTWREWFczK294OWhreitwK0c0Ck9PQ0ZScHh3dHd0NmVWWTJXZ2dD
            Zkh1TThaTWZkQmR2VUNFcEloRWlCUWsKLS0tICtUQmdtVVFkRHpIc1ZJeitXTmNZ
            bk9sREY3NnAyM1pLa0Z3VkFKYW1MM3MKKtVG0GcXS01OUrRlm/WFIwmCkMVUuZ3h
            PEWvLEYsWL7Dq9vq8V1srV5SgnC65ACNSxPE2TheP5kwqmUJFWulaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dcdy9jdwvq6nrsxdtvgs05fuyd9fgfx3x788aky3zcsfc6kmhajqt0d86w
    lastmodified: "2026-06-09T02:42:45Z"
    mac: ENC[AES256_GCM,data:P2hFXfgcwFwskwXLKlLOEpzBIwkMqZWoBixLqfg+kZIrxmsmpXfDUd3/i/9yVLymGb2S4GQp+pwnZ/JJGzMgMHFSXA2iAiuim4S/1y+ykWFh0X04y+SHyehA3QT5Ru9Jei23YWREz/1d4iZtd98V2H40B3QogbUvQbV5+i0BmnM=,iv:MtbntbFjMeVkhr3/CVUoSW0SUKsy8/DW5Kt1+bzMmFE=,tag:O5m6FnrRqrJy5EEFhONmUw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
