---
- name: Ensure sysusers.d directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /etc/sysusers.d
    - /etc/tmpfiles.d

- name: Configure ASF tmpfiles
  ansible.builtin.copy:
    dest: /etc/tmpfiles.d/asf.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      d /etc/asf 0755 root root -
      # Ensure nobody can access these configs
      d /etc/asf/config 0700 root root -
  notify: Apply asf tmpfiles

- name: Declaratively create ASF system user
  ansible.builtin.copy:
    dest: /etc/sysusers.d/asf.conf
    mode: "0644"
    content: |
      # Type Name  ID   GECOS                   Home directory Shell
      u      asf   -    "ArchiSteamFarm Daemon" /app/config    -
  notify: Apply asf sysusers

- name: Flush handlers to create ASF user
  ansible.builtin.meta: flush_handlers

- name: Fetch newly created ASF user info
  ansible.builtin.getent:
    database: passwd
    key: asf

- name: Ensure Quadlet directory exists
  ansible.builtin.file:
    path: /etc/containers/systemd
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Template ASF.json to centralized location
  ansible.builtin.template:
    src: ASF.json.j2
    dest: /etc/asf/config/ASF.json
    owner: "{{ ansible_facts.getent_passwd['asf'][1] }}"
    group: "{{ ansible_facts.getent_passwd['asf'][2] }}"
    mode: "0600"
    # Ensure changes via ASF Web UI aren't reverted
    force: false
  notify: Restart ASF

- name: Copy Tailscale serve.json to unified location
  ansible.builtin.copy:
    src: tailscale_serve.json
    dest: /etc/asf/serve.json
    owner: root
    group: root
    mode: "0644"
  notify: Restart Tailscale

- name: Store ArchiSteamFarm Tailscale Auth-Key as a Podman Secret
  containers.podman.podman_secret:
    name: ts_asf_key
    state: present
    data: "{{ tailscale_oauth_secret }}?ephemeral=false"
    force: true

- name: Deploy ASF Quadlets
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/containers/systemd/{{ item | regex_replace('\\.j2$', '') }}"
    owner: root
    group: root
    mode: "0644"
  vars:
    # Inject the dynamically assigned system UID/GID into the container template
    asf_user_id: "{{ ansible_facts.getent_passwd['asf'][1] }}"
    asf_group_id: "{{ ansible_facts.getent_passwd['asf'][2] }}"
  loop:
    - asf.network.j2
    - ts-asf-data.volume
    - ts-asf.container.j2
    - asf.container.j2
  notify:
    - Reload systemd
    - Restart ASF

- name: Ensure ASF service is started
  ansible.builtin.systemd:
    daemon_reload: true
    name: asf.service
    state: started
    enabled: true
