---
- name: Ensure Quadlet directory exists
  ansible.builtin.file:
    path: /etc/containers/systemd
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Ensure Pocket ID encryption key is provided
  ansible.builtin.assert:
    that:
      - pocket_id_encryption_key != ""
    fail_msg: "You must define pocket_id_encryption_key to deploy Pocket ID."

- name: Store Pocket ID Encryption Key as a Podman Secret
  containers.podman.podman_secret:
    name: pocket_id_encryption_key
    state: present
    data: "{{ pocket_id_encryption_key }}"
    force: true

- name: Deploy Pocket ID Quadlets
  ansible.builtin.template:
    owner: root
    group: root
    mode: "0644"
    dest: "/etc/containers/systemd/{{ item | regex_replace('\\.j2$', '') }}"
    src: "{{ item }}"
  loop:
    - pocket-id.network.j2
    - pocket-id-data.volume
    - pocket-id.container.j2
  notify:
    - Reload systemd
    - Restart Pocket ID

- name: Ensure Pocket ID service is enabled and started
  ansible.builtin.systemd:
    daemon_reload: true
    name: pocket-id.service
    state: started
    enabled: true
