---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Rebuild keep-vm-alive container
  ansible.builtin.systemd:
    name: keep-vm-alive-build.service
    state: restarted

- name: Restart keep-vm-alive
  ansible.builtin.systemd:
    name: keep-vm-alive.service
    state: restarted
