---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Apply caddy tmpfiles
  ansible.builtin.command: systemd-tmpfiles --create /etc/tmpfiles.d/caddy.conf
  changed_when: true

- name: Rebuild caddy container
  ansible.builtin.systemd:
    name: caddy-build.service
    state: restarted

- name: Restart Caddy
  ansible.builtin.systemd:
    name: caddy.service
    state: restarted

- name: Reload Crowdsec
  ansible.builtin.systemd:
    name: crowdsec.service
    state: restarted
