---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Rebuild caddy container
  ansible.builtin.systemd:
    name: caddy-build.service
    state: restarted

- name: Restart Caddy
  ansible.builtin.systemd:
    name: caddy.service
    state: restarted

- name: Reload Caddy
  ansible.builtin.systemd:
    name: caddy.service
    state: reloaded

- name: Reload Crowdsec
  ansible.builtin.systemd:
    name: crowdsec.service
    state: restarted

- name: Restart Firewall Bouncer
  ansible.builtin.systemd:
    name: cs-firewall.service
    state: restarted
