apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pocket-id-credentials
spec:
    secretTemplates:
        - name: pocket-id-credentials
          stringData:
            ENCRYPTION_KEY: ENC[AES256_GCM,data:0/oHVApmlAe5Xma4bFn1zXztxG0Ylb1boTsFgdyhQePXAGUJF5rVAlNMjFvW,iv:WlRPxU1s4DroNGSMPHLRj/miSEPaIFoXc9UBW+u2/qU=,tag:j+/AZW8ot95s/B/1uEH2KA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYWJwVllXb2ZEZDRtamtH
            RmFhSU1BMG9vRzZpSjhFVkJPK01PdWhtY3dZCi9wWWZwaTBGSVYvM3FqWGVFUnZs
            UGZ0RGJSWTJrOVVtSU9tRFlPU0swWmcKLS0tIDZqZVBjS0pNN2k1cWhwck8yejkz
            WnBaNy9OczgyRm5xMGE2M0NTSEdlK2MKnny+8/ulOXzscKSgm3PfwPWQlNL7JIyV
            8SHL5eDUEDY3gNRJ3Mu6ZKHuKLIxhZMabvzgMCmmH8HxLx1QgxcI8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dcdy9jdwvq6nrsxdtvgs05fuyd9fgfx3x788aky3zcsfc6kmhajqt0d86w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T22:32:39Z"
    mac: ENC[AES256_GCM,data:8bRKsApAbKoy43MXY6tzvykyoKg+t0CdjRz6coXduyKJ9pCfI6lm4Fgeb7XdNcR2AdjLcHGGBwkJzU/2tkaURRtqCgQ9fOBx84zwjiPOqJv1FsYUSqK5eOr3we5jdVr8bIDNSyHlrdrMyJ4JBULmKTS7xq2CVDebnbWVXgGox2Q=,iv:K7gVujsb0P1j9mdSAsPdFhgpqexgid44IU/sIehQe20=,tag:VYGDqOyU6bTOYLQA/Z5sOQ==,type:str]
    version: 3.13.3
