apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pocket-id-credentials
spec:
    secretTemplates:
        - name: pocket-id-credentials
          stringData:
            ENCRYPTION_KEY: ENC[AES256_GCM,data:DfSYJUya0Y9/W2iuN9Ulme8cvwwMIYaeVCZ7xm4yPNi1QtwLJmsGIVYtkEA=,iv:5v7j0ZEC9iocSk4wycV02vgJJiRT9OuRqOJI3E/H2JM=,tag:eyOXDJsEiDKW7KLd7yDVsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYWJwVllXb2ZEZDRtamtH
            RmFhSU1BMG9vRzZpSjhFVkJPK01PdWhtY3dZCi9wWWZwaTBGSVYvM3FqWGVFUnZs
            UGZ0RGJSWTJrOVVtSU9tRFlPU0swWmcKLS0tIDZqZVBjS0pNN2k1cWhwck8yejkz
            WnBaNy9OczgyRm5xMGE2M0NTSEdlK2MKnny+8/ulOXzscKSgm3PfwPWQlNL7JIyV
            8SHL5eDUEDY3gNRJ3Mu6ZKHuKLIxhZMabvzgMCmmH8HxLx1QgxcI8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dcdy9jdwvq6nrsxdtvgs05fuyd9fgfx3x788aky3zcsfc6kmhajqt0d86w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T22:36:11Z"
    mac: ENC[AES256_GCM,data:dEv8uZLMd7h0BME6Bu9bbGVE0RG3FiV06KUUZQoWsB7fQauJR+aPFqyRvvVlkPcbSY4NFMj4WJXfZtsnn9RJqDnxDty6r58pIAM19k/aPw4KvlcGfgIPcFTBMGwSlpHl63JynF7cwkpjopUL8tbo6Rlth+Pju21jlCs3j1fRMn8=,iv:alRBtLXeFdMAOVMLkjMj0gz/J6txbFMokj8U6eJLsnI=,tag:X/fAiyWEeCMAcU5/UIrzKw==,type:str]
    version: 3.13.3
