---
# Playbook for the server shu
- name: Setup VPS
  hosts: all
  become: true

  tasks:
    - name: Set configured services list
      ansible.builtin.set_fact:
        configured_services: "{{ (group_services | default([])) + (host_services | default([])) }}"

    - name: Set services to configure list
      ansible.builtin.set_fact:
        # If 'svcs' is defined, split it by comma and trim whitespace.
        # Otherwise, default to configured_services.
        services: "{{ svcs.split(',') | map('trim') | list if svcs is defined else configured_services }}"

    - name: Load host-specific settings for {{ inventory_hostname }}
      community.sops.load_vars:
        file: "vars/settings.{{ inventory_hostname }}.yaml"
        age_keyfile: .age-key.txt
      # Build the string using Jinja concatenation, then check if it's a file
      when: >
        ('vars/settings.' ~ inventory_hostname ~ '.yaml') is file

    # -----------------------------------------------------------
    # Base Setup (skipped if svcs is provided)
    # -----------------------------------------------------------

    - name: Setup Tailscale optimizations (Base)
      ansible.builtin.include_role:
        name: tailscale
      when: svcs is not defined

    - name: Setup podman (Base)
      ansible.builtin.include_role:
        name: podman
      when: svcs is not defined

    - name: Setup cockpit (Base)
      ansible.builtin.include_role:
        name: cockpit
      when: svcs is not defined

    # -----------------------------------------------------------
    # Service Loop
    # -----------------------------------------------------------

    - name: Setup services
      ansible.builtin.include_role:
        name: "{{ service_item }}"
      loop_control:
        loop_var: service_item
      loop: "{{ services }}"
