---
# Playbook for the server shu
- name: Setup VPS
  hosts: all

  tasks:
    - name: Get DEB architecture
      ansible.builtin.command: dpkg --print-architecture
      register: deb_architecture
      changed_when: false

    - name: Setup User, SSH, and UFW
      ansible.builtin.import_role:
        name: common

    - name: Setup service {{ item }}
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ services.split(',') }}"
      vars:
        syncthing_username: "{{ username }}"
        docker_username: "{{ username }}"
