---
# Playbook for the server shu
- name: Setup VPS
  hosts: all
  gather_facts: false

  tasks:
    - name: Setup User, SSH, and UFW
      ansible.builtin.import_role:
        name: common

    - name: Setup service {{ item }}
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ services.split(',') }}"
      vars:
        syncthing_username: "{{ username }}"
