---
# Playbook for the server shu
- name: Setup VPS
  hosts: all

  tasks:
    - name: Set configured services list
      ansible.builtin.set_fact:
        configured_services: "{{ (group_services | default([])) + (host_services | default([])) }}"

    - name: Set services to configure list
      ansible.builtin.set_fact:
        # If 'svcs' is defined, split it by comma and trim whitespace.
        # Otherwise, default to configured_services.
        services: "{{ svcs.split(',') | map('trim') | list if svcs is defined else configured_services }}"

    - name: Check tailscale status
      ansible.builtin.command: tailscale status --json
      register: tailscale_status
      check_mode: false
      changed_when: false

    - name: Set tailscale_is_running
      ansible.builtin.set_fact:
        tailscale_active: "{{ (tailscale_status.stdout | from_json).Self.Online }}"

    - name: Check tailscale serve status
      ansible.builtin.command: tailscale serve status --json
      register: tailscale_serve_status
      check_mode: false
      changed_when: false

    - name: Set tailscale_serve_status as a dict
      ansible.builtin.set_fact:
        tailscale_serve_status: "{{ (tailscale_serve_status.stdout | from_json) }}"

    - name: Get DEB architecture
      ansible.builtin.command: dpkg --print-architecture
      register: deb_architecture
      check_mode: false
      changed_when: false

    - name: Load vars/settings.local.yaml
      delegate_to: localhost
      ansible.builtin.include_vars:
        file: vars/settings.local.yaml
      when: "'vars/settings.local.yaml' is file"

    # -----------------------------------------------------------
    # Base Setup (skipped if svcs is provided)
    # -----------------------------------------------------------

    - name: Setup User, SSH, and UFW (Base)
      ansible.builtin.import_role:
        name: common
      # Only run this explicitly if we are NOT overriding the service list
      when: svcs is not defined

    - name: Setup docker (Base)
      ansible.builtin.include_role:
        name: docker
      vars:
        docker_username: "{{ username }}"
      when: svcs is not defined

    # -----------------------------------------------------------
    # Service Loop
    # -----------------------------------------------------------

    - name: Setup services
      ansible.builtin.include_role:
        name: "{{ service_item }}"
      loop_control:
        loop_var: service_item
      loop: "{{ services }}"
      vars:
        syncthing_username: "{{ username }}"
        docker_username: "{{ username }}"
