apiVersion: v1
kind: ConfigMap
metadata:
  name: pomerium-config
data:
  config.yaml: |
    insecure_server: true
    address: ":8080"
    grpc_address: "127.0.0.1:5443"
    idp_provider: "oidc"
    idp_provider_url: "https://id.maxice8.com"
    authenticate_service_url: "https://pomerium.maxice8.com"

    routes:
      - name: "ArchiSteamFarm"
        description: "Steam Accounts"
        from: "https://asf.mashu.maxice8.com"
        to: "http://asf.asf.svc.cluster.local:1242"
        policy:
          - allow:
              or:
                - authenticated_user: true
      - name: "Syncthing"
        description: "File Synchronization"
        from: "https://syncthing.mashu.maxice8.com"
        to: "http://syncthing.syncthing.svc.cluster.local:8384"
        policy:
          - allow:
              or:
                - authenticated_user: true
      - name: "Netdata"
        description: "System Monitoring"
        from: "https://netdata.mashu.maxice8.com"
        to: "http://netdata.netdata.svc.cluster.local:19999"
        policy:
          - allow:
              or:
                - authenticated_user: true
      - name: "Backrest"
        description: "Backup Management"
        from: "https://backrest.mashu.maxice8.com"
        to: "http://backrest.backrest.svc.cluster.local:9898"
        policy:
          - allow:
              or:
                - authenticated_user: true
      - name: "Argus"
        description: "Release Monitoring"
        from: "https://argus.mashu.maxice8.com"
        to: "http://argus.argus.svc.cluster.local:8080"
        allow_websockets: true
        policy:
          - allow:
              or:
                - authenticated_user: true
