apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pomerium-credentials
spec:
    secretTemplates:
        - name: pomerium-credentials
          stringData:
            IDP_CLIENT_ID: ENC[AES256_GCM,data:3NIoh58V7Jt9LqFPd40rTbAkO5URhlaTneoGcxeu+/wKrSyBHes=,iv:pA2zkg7KIolXkH8ctFULBk4B3N4KJI0yYEAzt40EM4E=,tag:MFQgWsb0VS3zevthTntVaQ==,type:str]
            IDP_CLIENT_SECRET: ENC[AES256_GCM,data:7X6do0qUqC5w7YQ1gVDim55jjZUEBmQtHof+R/cpKDqI/w==,iv:4JwjDAQKBmU8L2lPcLyn1D1fY107SxxasZwEAF2tdu8=,tag:zO1xaqFeAjopnMAUbsIUSg==,type:str]
            COOKIE_SECRET: ENC[AES256_GCM,data:da1SaF6NfM7Jq3jJGV3n7rDxj5+jDOuMl3o9mzJkkCqO7MC88K6MTOkDenQcQw==,iv:yctQokTXu53HgBALtPxHuagtWDBXW+0v1M7/0IqZVcQ=,tag:fvUtKqYygw6un7g7ePClCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdVBubERXa2NwbThweTEz
            cVRISlZ2cFBQc3NCclJySk9qeUVyYXBrUEFJCjVRYzFjY0xNRGJINzNreXF3YTFI
            aUF1VnZSUHNlNHJUd0lOQmFrUXVTS0UKLS0tIHppN0ZPd1VnOUU4UWxXb09ybERB
            QmZBZCtpU2xJWDdWMVBLcDlaUWd6YmcKz5aivC0RGddcbk9ode8rKqc6NTQxsKy9
            n5o4v5BWpb/RQwgzQpP79ZTzraaR79zKkM7GreALEDhZpjqYmqkQ/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dcdy9jdwvq6nrsxdtvgs05fuyd9fgfx3x788aky3zcsfc6kmhajqt0d86w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T22:25:00Z"
    mac: ENC[AES256_GCM,data:yVSNAmUfrJ4+m53dkKk0uIeGQBNZ2xvrHnwDqH9yGkjda24MueNnDQz/SqC4vHLT79q5AJvtgE8fZq4nzxpeMEPx7T+uAQ+IrxjZEIav6ODbnCLDEC66rDFsG5ATcPcZ2b/xHFR1NEgO6mjdfkj9u0jlAplLOJi7A2sas+v7Q4s=,iv:CPP78vUXNIh+5Xdivy1ysdxYdsXb4fX0t//qkNuxQJE=,tag:wcYIn6Qna+h6xCKuVKw2ZA==,type:str]
    version: 3.13.3
