apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pomerium-credentials
spec:
    secretTemplates:
        - name: pomerium-credentials
          stringData:
            IDP_CLIENT_ID: ENC[AES256_GCM,data:YCp3bKXJW0Hu4hKG+1IeFpD94g1yMAUdhfrPXnoT7cDeU7BW,iv:+WwKfVvrTPOVI4uUN6RiQF12MSIw1SsM4x7No4g0Nek=,tag:NMVsZsiXww7tBCwOvZgoHA==,type:str]
            IDP_CLIENT_SECRET: ENC[AES256_GCM,data:rjPco4VExbc9Suk7HtPk7J9eqTH/6ymyLb11jGxjhso=,iv:SvD8KPzTY/3CV4tvE0O4eu9QFgaTG3aoeLAfgaYlYrg=,tag:YTZZAnO8guk1RiZTvmJPyQ==,type:str]
            COOKIE_SECRET: ENC[AES256_GCM,data:dPTfEKdFJco1oqox7VyoIoPTFHqq6Hrqq7WgQgaCekCaggmE5Bo/8LuyXSQ=,iv:Q+Gj0sESBePU5SyXsiKXMpcFz9E/MKl1/NguJTZDhcU=,tag:LnUAVylaMIBYQ6MPxDs6DQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdVBubERXa2NwbThweTEz
            cVRISlZ2cFBQc3NCclJySk9qeUVyYXBrUEFJCjVRYzFjY0xNRGJINzNreXF3YTFI
            aUF1VnZSUHNlNHJUd0lOQmFrUXVTS0UKLS0tIHppN0ZPd1VnOUU4UWxXb09ybERB
            QmZBZCtpU2xJWDdWMVBLcDlaUWd6YmcKz5aivC0RGddcbk9ode8rKqc6NTQxsKy9
            n5o4v5BWpb/RQwgzQpP79ZTzraaR79zKkM7GreALEDhZpjqYmqkQ/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dcdy9jdwvq6nrsxdtvgs05fuyd9fgfx3x788aky3zcsfc6kmhajqt0d86w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T22:42:42Z"
    mac: ENC[AES256_GCM,data:OgWge9DlgzqVuJekapdYjpuK07g7kgBQGu6jCcdF9vTxlAp272MteSxD/idwQyqjASjwHCoiKd4l3yjsJB8N+6b39wUna8npivgUz8uCZ1zvfiyGqQ5qDqTB7+zOG/z+0GUN4HAOlR+S7hF1Y3FdkORMUzVGCq61ONyRv21xvg4=,iv:LTIrietrBCAaKONaXDiNkeOTtn+Mo/0iZWSh7d9U7tA=,tag:/E+gu2XSekIix4S7k7dACA==,type:str]
    version: 3.13.3
