---
- name: Run watchtower container
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower
    state: started
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
