name: Ansible Lint
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master", "stable", "release/v*"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint with Docker Image
        # This runs the command directly inside the container
        uses: docker://pipelinecomponents/ansible-lint:latest
        with:
          args: "ansible-lint"
