---
- name: Ensure Podman socket is enabled (for container metrics)
  ansible.builtin.systemd:
    name: podman.socket
    state: started
    enabled: true

- name: Configure Netdata tmpfiles
  ansible.builtin.copy:
    dest: /etc/tmpfiles.d/netdata.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      d /etc/netdata 0755 root root -
  notify: Apply netdata tmpfiles

- name: Flush handlers to create Netdata directories
  ansible.builtin.meta: flush_handlers

- name: Create health_alarm_notify.conf on host
  ansible.builtin.template:
    owner: root
    group: root
    mode: "0644"
    src: health_alarm_notify.conf.j2
    dest: /etc/netdata/health_alarm_notify.conf
  notify: Restart Netdata

- name: Ensure Quadlet directory exists
  ansible.builtin.file:
    path: /etc/containers/systemd
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy Netdata Quadlets
  ansible.builtin.template:
    owner: root
    group: root
    mode: "0644"
    dest: "/etc/containers/systemd/{{ item | regex_replace('\\.j2$', '') }}"
    src: "{{ item }}"
  loop:
    # Config volume successfully removed!
    - netdata-lib.volume
    - netdata-cache.volume
    - netdata.container.j2
  notify:
    - Reload systemd
    - Restart Netdata

- name: Flush handlers to start Netdata container
  ansible.builtin.meta: flush_handlers

- name: Expose Netdata through Tailscale
  ansible.builtin.command: tailscale serve --service=svc:netdata --https=443 localhost:19999
  # Tailscale serve is idempotent in configuration but doesn't report status changes simply, so we silence the change status.
  changed_when: false

- name: Deploy Netdata Heartbeat Service and Timer
  when: (heartbeat_netdata | default('')) != ""
  block:
    - name: Create Netdata Heartbeat Service
      ansible.builtin.copy:
        dest: /etc/systemd/system/netdata-heartbeat.service
        mode: "0644"
        content: |
          [Unit]
          Description=Netdata Heartbeat

          [Service]
          Type=oneshot
          ExecStart=/bin/sh -c \
            'podman inspect --format "{% raw %}{{ .State.Health.Status }}{% endraw %}" netdata | \
            grep -q healthy && \
            curl -fsS -m 5 --retry 3 {{ heartbeat_netdata }} > /dev/null'

    - name: Create Netdata Heartbeat Timer
      ansible.builtin.copy:
        dest: /etc/systemd/system/netdata-heartbeat.timer
        mode: "0644"
        content: |
          [Unit]
          Description=Netdata Heartbeat Timer

          [Timer]
          OnCalendar=*:0/5
          Persistent=true

          [Install]
          WantedBy=timers.target

    - name: Enable and start Netdata Heartbeat Timer
      ansible.builtin.systemd:
        name: netdata-heartbeat.timer
        enabled: true
        state: started
        daemon_reload: true
