---
- name: Create Caddy directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /etc/caddy
    - /var/log/caddy

- name: Copy Dockerfile for custom build
  ansible.builtin.copy:
    src: Dockerfile
    dest: /etc/caddy/Dockerfile
    owner: root
    group: root
    mode: "0644"
  notify: Restart Caddy Build

- name: Template Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: "0644"
  notify: Restart Caddy

- name: Ensure Quadlet directory exists
  ansible.builtin.file:
    path: /etc/containers/systemd
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy Caddy Quadlets
  ansible.builtin.template:
    owner: root
    group: root
    mode: "0644"
    dest: "/etc/containers/systemd/{{ item | regex_replace('\\.j2$', '') }}"
    src: "{{ item }}"
  loop:
    - caddy-data.volume
    - caddy.build
    - caddy.container.j2
  notify:
    - Reload systemd
    - Restart Caddy

- name: Import crowdsec support
  ansible.builtin.include_tasks: crowdsec.yaml
  when: caddy_crowdsec_api_key != ""

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure Caddy service is started
  ansible.builtin.systemd:
    name: caddy.service
    state: started
    enabled: true
