---
- name: Ensure /etc/tmpfiles.d exists
  ansible.builtin.file:
    path: /etc/tmpfiles.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Configure Caddy tmpfiles
  ansible.builtin.copy:
    dest: /etc/tmpfiles.d/caddy.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      d /etc/caddy 0755 root root -
      d /var/log/caddy 0755 root root -
  notify: Apply caddy tmpfiles

- name: Flush handlers to create Caddy directories
  ansible.builtin.meta: flush_handlers

- name: Copy Containerfile for custom build
  ansible.builtin.copy:
    src: Containerfile
    dest: /etc/caddy/Containerfile
    owner: root
    group: root
    mode: "0644"
  notify: Rebuild caddy container

- name: Template Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: "0644"
  notify: Restart Caddy

- name: Ensure Quadlet directory exists
  ansible.builtin.file:
    path: /etc/containers/systemd
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Store Caddy CrowdSec API Key in a Podman Secret
  containers.podman.podman_secret:
    name: caddy_crowdsec_api_key
    state: present
    data: "{{ caddy_crowdsec_api_key }}"
    force: true
  when: caddy_crowdsec_api_key != ""

- name: Deploy Caddy Quadlets
  ansible.builtin.template:
    owner: root
    group: root
    mode: "0644"
    dest: "/etc/containers/systemd/{{ item | regex_replace('\\.j2$', '') }}"
    src: "{{ item }}"
  loop:
    - caddy-data.volume
    - caddy.build
    - caddy.container.j2
  notify:
    - Reload systemd
    - Restart Caddy

- name: Flush handlers for Caddy
  ansible.builtin.meta: flush_handlers

- name: Ensure Caddy service is started
  ansible.builtin.systemd:
    name: caddy.service
    state: started
    enabled: true

- name: Import CrowdSec Support
  ansible.builtin.include_tasks: crowdsec.yaml
  when: caddy_crowdsec_api_key != ""

- name: Import CrowdSec Firewall Bouncer Support
  ansible.builtin.include_tasks: crowdsec-firewall-bouncer.yaml
  when:
    - caddy_crowdsec_api_key != ""
    - cs_firewall_bouncer_key != ""
