apiVersion: 1

prune: true

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: "https://prometheus.neko-great.ts.net"
    version: 1
    isDefault: true
    editable: true
