apiVersion: 1

prune: true

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: "http://prometheus:9090"
    version: 1
    isDefault: true
    editable: true
