apiVersion: 1

prune: true

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: "https://mika.neko-great.ts.net:9090"
    version: 1
    isDefault: true
    editable: true
