---
- name: Ensure sysusers.d directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /etc/sysusers.d
    - /etc/tmpfiles.d

- name: Declaratively create Forgejo system user
  ansible.builtin.copy:
    dest: /etc/sysusers.d/forgejo.conf
    mode: "0644"
    content: |
      # Type Name     ID   GECOS             Home directory Shell
      u      forgejo  -    "Forgejo Daemon"  /data          -
  notify: Apply forgejo sysusers

- name: Configure Forgejo tmpfiles
  ansible.builtin.copy:
    dest: /etc/tmpfiles.d/forgejo.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      d /etc/forgejo 0755 root root -
  notify: Apply forgejo tmpfiles

- name: Flush handlers to create Forgejo user
  ansible.builtin.meta: flush_handlers

- name: Fetch newly created Forgejo user info
  ansible.builtin.getent:
    database: passwd
    key: forgejo

- name: Ensure Quadlet directory exists
  ansible.builtin.file:
    path: /etc/containers/systemd
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Store tailscale auth-key as a podman secret
  containers.podman.podman_secret:
    name: ts_forgejo_key
    state: present
    data: "{{ container_tsclient_key }}?ephemeral=false"
    force: true

- name: Deploy Tailscale Sidecar Quadlets
  ansible.builtin.template:
    owner: root
    group: root
    mode: "0644"
    dest: "/etc/containers/systemd/{{ item | regex_replace('\\.j2$', '') }}"
    src: "{{ item }}"
  loop:
    - ts-forgejo-data.volume
    - ts-forgejo.container.j2
  notify:
    - Reload systemd
    - Restart Tailscale

- name: Deploy Forgejo Server Quadlets
  ansible.builtin.template:
    owner: root
    group: root
    mode: "0644"
    dest: "/etc/containers/systemd/{{ item | regex_replace('\\.j2$', '') }}"
    src: "{{ item }}"
  vars:
    # Inject the dynamically assigned system UID/GID into the container template
    forgejo_user_id: "{{ ansible_facts.getent_passwd['forgejo'][1] }}"
    forgejo_group_id: "{{ ansible_facts.getent_passwd['forgejo'][2] }}"
  loop:
    - forgejo-data.volume
    - forgejo.container.j2
  notify:
    - Reload systemd
    - Restart Forgejo

- name: Ensure Forgejo service is started
  ansible.builtin.systemd:
    daemon_reload: true
    name: forgejo.service
    state: started
