- name: Ensure sysusers.d directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /etc/sysusers.d
    - /etc/tmpfiles.d

- name: Declaratively create Forgejo system user
  ansible.builtin.copy:
    dest: /etc/sysusers.d/forgejo.conf
    mode: "0644"
    content: |
      # Type Name     ID   GECOS             Home directory Shell
      u      forgejo  -    "Forgejo Daemon"  /data          -
  register: forgejo_sysusers_config

- name: Apply forgejo sysusers immediately # noqa: no-handler
  ansible.builtin.command: systemd-sysusers /etc/sysusers.d/forgejo.conf
  changed_when: true
  when: forgejo_sysusers_config.changed

- name: Fetch newly created Forgejo user info
  ansible.builtin.getent:
    database: passwd
    key: forgejo

- name: Ensure Quadlet directory exists
  ansible.builtin.file:
    path: /etc/containers/systemd
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy Forgejo Server Quadlets
  ansible.builtin.template:
    owner: root
    group: root
    mode: "0600"
    dest: "/etc/containers/systemd/{{ item | regex_replace('\\.j2$', '') }}"
    src: "{{ item }}"
  vars:
    forgejo_user_id: "{{ ansible_facts.getent_passwd['forgejo'][1] }}"
    forgejo_group_id: "{{ ansible_facts.getent_passwd['forgejo'][2] }}"
  loop:
    - forgejo.network.j2
    - forgejo-data.volume
    - forgejo.container.j2
  notify:
    - Reload systemd
    - Restart Forgejo

- name: Ensure Forgejo service is started
  ansible.builtin.systemd:
    daemon_reload: true
    name: forgejo.service
    state: started
