apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backrest
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.maxice8.com/max/ansible.git
    targetRevision: master
    path: kubernetes/platform/backrest
  destination:
    server: https://kubernetes.default.svc
    namespace: backrest
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
