apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway-system-namespace.yaml
  - netdata-namespace.yaml
  - gateway-api.yaml
  - traefik.yaml
  - public-gateway.yaml
  - cert-manager.yaml
  - sops-secrets-operator.yaml
  - argus.yaml
  - syncthing.yaml
  - certificate-issuers.yaml
  - forgejo.yaml
  - forgejo-runner.yaml
  - staging-certificate.yaml
  - production-certificate.yaml
  - backrest.yaml
  - rancher.yaml
  - rancher-compliance.yaml
  - platform-routes.yaml
  - whoami.yaml
  - pingvin-share.yaml
  - asf.yaml
  - pocket-id.yaml
  - pomerium.yaml
  - netbird.yaml
  - netbird-dashboard.yaml
  - netdata.yaml
