apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../platform/argocd
  - gateway-api.yaml
  - traefik.yaml
  - public-gateway.yaml
  - cert-manager.yaml
  - sops-secrets-operator.yaml
  - certificate-issuers.yaml
  - staging-certificate.yaml
  - production-certificate.yaml
  - backrest.yaml
  - rancher.yaml
  - platform-routes.yaml
  - whoami.yaml
  - pingvin-share.yaml
  - asf.yaml
  - pocket-id.yaml
  - pomerium.yaml
