apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-routes
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.maxice8.com/max/ansible.git
    targetRevision: master
    path: kubernetes/platform/routes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
