apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: public-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://git.maxice8.com/max/ansible.git
    targetRevision: master
    path: kubernetes/platform/public-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
