apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://releases.rancher.com/server-charts/latest
    chart: rancher
    targetRevision: 2.15.0
    helm:
      releaseName: rancher
      valuesObject:
        hostname: rancher.maxice8.com
        replicas: 1
        ingress:
          enabled: false
        tls: external
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
