apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sops-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: default
  source:
    repoURL: https://isindir.github.io/sops-secrets-operator
    chart: sops-secrets-operator
    targetRevision: 0.28.1
    helm:
      releaseName: sops-secrets-operator
      values: |
        image:
          tag: "0.21.2"
          pullPolicy: IfNotPresent

        initImage:
          tag: "26.04"
          pullPolicy: IfNotPresent

        extraEnv:
          - name: SOPS_AGE_KEY_FILE
            value: /etc/sops-age/keys.txt

        secretsAsFiles:
          - name: age-identity
            mountPath: /etc/sops-age
            secretName: sops-age-identity

        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi

        securityContext:
          enabled: true
          container:
            enabled: true
            customContainerSecurityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
  destination:
    server: https://kubernetes.default.svc
    namespace: sops-secrets-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
