apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 41.3.0
    helm:
      releaseName: traefik
      values: |
        image:
          tag: v3.7.11
          pullPolicy: IfNotPresent

        deployment:
          replicas: 1
          dnsPolicy: ClusterFirstWithHostNet

        hostNetwork: true

        updateStrategy:
          type: Recreate
          rollingUpdate: null

        ingressClass:
          enabled: false

        providers:
          kubernetesCRD:
            enabled: false
          kubernetesIngress:
            enabled: false
          kubernetesGateway:
            enabled: true
            experimentalChannel: false

        gateway:
          enabled: false

        additionalArguments:
          - --entryPoints.web.http.redirections.entryPoint.to=:443
          - --entryPoints.web.http.redirections.entryPoint.scheme=https
          - --entryPoints.web.http.redirections.entryPoint.permanent=true

        ports:
          traefik:
            port: 9000
          web:
            port: 8000
          websecure:
            port: 8443

        service:
          spec:
            type: ClusterIP

        log:
          level: INFO

        accessLog:
          enabled: true

        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
