apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-mashu-maxice8-com-staging
  namespace: gateway-system
spec:
  secretName: wildcard-mashu-maxice8-com-staging
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-staging
  dnsNames:
    - mashu.maxice8.com
    - "*.mashu.maxice8.com"
