services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    network_mode: host
    environment:
      - GF_SERVER_HTTP_PORT=33000
    volumes:
      - 'storage:/var/lib/grafana'
      - ./provisioning:/etc/grafana/provisioning
    healthcheck:
      test: "curl -f http://localhost:33000/api/health"
      interval: 15s
      timeout: 30s
      retries: 3

volumes:
  storage: {}