services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    network_mode: host
    volumes:
      - 'storage:/var/lib/grafana'
    healthcheck:
      test: "curl -f http://localhost:3000/api/health"
      interval: 15s
      timeout: 30s
      retries: 3

volumes:
  storage: {}