apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: backrest-credentials
    namespace: backrest
spec:
    secretTemplates:
        - name: backrest-credentials
          stringData:
            id_ed25519: ENC[AES256_GCM,data:9wgvycwewucQ2W93swPFJPzIUmQZhfXXETTxENBgqajF8XO0sqQ2p4SyQ0xpWg9DFUyg3vmL4izm4WvhEclJUds3RUsUMEcfo7h6QaWK+cEb2YW5sQ7z7FtQ9GxcbzzZr7g3AzJKFu8AIg1WvK9YUJKt+JjuLHd9JYWqqAZCs5u3O2FdJZwI8KoGYdJ4IVlkd4gq+3hT90CeCEc5PgjtTx+T9jBUpnN5jtTcmhRwisRuUfZ1K9Vlx8ySx68iuVUN9SsqUy/5xneoQ1mzi9Yv3dxrud5cgC/xeWiGrXycPO/RUvxjKueWPCCCe6OsWkLDo37BiUTEqX8hQqx/k1rHaekPvDz7TgxaJLFvre/1nzRp196AR1cSWfrMRBvlDH51i/h8dFH2fcux2w477berJaOZm0978+++7HzfbUd98emm1sypj595DBmLZgL2NOGht3j3kW1yDZnRZoqetJxV8Nh0nXotqMqNicPFa1mVjDULvC2VljxyKij2NZzslWcVbfvO4WV4R10DuK7BrMFilkcoJdvverSoKq7i,iv:5H098ikqoL5cA2H5E7vJC+ZnOLF/+vqehVkjBTilgQs=,tag:TkDsWszaa2BEmmPHMH/XwA==,type:str]
            id_ed25519.pub: ENC[AES256_GCM,data:ycf1a69CnAczrdCtVCs01xo8ewuetlPFGF6XeMS0p9pzqwc33AJjcd4TBuINrQpETNQLP8doFUYrULsGZlSgNxTuGCgP7ZwgyVSF/D1nCDkeunzXTbKzyhuWkH6kQGLB,iv:4s7DgjfzlCVCxB4/5bWk4mBwGRJpURhnchkLfNx5RJg=,tag:vc1Mb7UkTwW6P5vw2NSvcA==,type:str]
            known_hosts: ENC[AES256_GCM,data:Sm2uM+s05wht9661WRjkItymIX18xOZ6KtOusHRZaaKoNAKo8Sloy4aWZY31tCP1YpA95JaawNn7SR9FtEhMTxeVQ/MugkvKiIwLAL/3NGhzEZCyxDPUA0yw/sBH8v5qkRkaudtW1FChFnz4Ct0qEs4=,iv:HpMMvs831RjK5Qv2KNrYfkNYBRrDPSlCbflYI9UP6HA=,tag:ij7oPHe+jwdrtavT/89tOQ==,type:str]
            repository-password: ENC[AES256_GCM,data:T2X1Xy9zSCU+eKvkil2VdLo54SAJkKPDZr3RSEDGGFaErcjNzucaGYGy1cnYzvol3oBizT9uOy6bpD4FwfmjCNY=,iv:XfZQASTICA2bVPjGfaUcCK7kdDn+FsPadSIWQmuVNsI=,tag:uL8Fk2HHNny1sh9vcBTxCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WE5jKzZuWkZoK3U4a3hE
            d1NMcW91SDgyOVZEQ2lSM0RwS2N2T1dyTWxzCmJsdktmRzVYRElYckF5dS9KVElW
            TVhzSTlYNkxJc0FQYkJSNVg0SlR6M00KLS0tIDJVdS82M1JFMVorbHA0ejRPWXpz
            S1hXNUxsWjJ3WEhIRmZDcXUrV0JNN0kKT1yXjbewqI3PdwLHT0K4oZcfuztz1yNH
            kUxfHGKCASRAKoVWeEXwv35DIbBNgbiLeNmXeaYKhrkyNO5Rj7JuhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dcdy9jdwvq6nrsxdtvgs05fuyd9fgfx3x788aky3zcsfc6kmhajqt0d86w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T21:16:36Z"
    mac: ENC[AES256_GCM,data:icIld596wAoGl4zNbmfFwYyCaGJX2d2ZJZJF7QvGTiIFyCOLbAWx+REM8z13qEn6Csbjo7rwttdvLBkuLf3KVCjHcsfY6z/q/hC4ZAG3wN4OfnmxFG1PzR0PDndFQe7Dp/A04f/zhAR3Eb1uIujxTUMs67ex2f/298v2/6cbruc=,iv:n8NJlK3deWRF4/bGFifvuyT1sKjZ3s90/Y45+V4daEM=,tag:q5ojnFkY2MJiYDDzlBtWuw==,type:str]
    version: 3.13.3
