---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Apply syncthing sysusers
  ansible.builtin.command: systemd-sysusers /etc/sysusers.d/syncthing.conf
  changed_when: true

- name: Apply syncthing tmpfiles
  ansible.builtin.command: systemd-tmpfiles --create /etc/tmpfiles.d/syncthing.conf
  changed_when: true

- name: Restart Tailscale
  ansible.builtin.systemd:
    name: ts-syncthing.service
    state: restarted

- name: Restart Syncthing
  ansible.builtin.systemd:
    name: syncthing.service
    state: restarted
