---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Tailscale
  ansible.builtin.systemd:
    name: ts-syncthing.service
    state: restarted

- name: Restart Syncthing
  ansible.builtin.systemd:
    name: syncthing.service
    state: restarted
