---
- name: Create /srv/monitoring/grafana directory
  ansible.builtin.file:
    owner: root
    group: root
    mode: "0755"
    path: /srv/monitoring/grafana
    state: directory

- name: Get list of managed provisioning files
  ansible.builtin.find:
    path: roles/monitoring/files/grafana/provisioning
    recurse: true
  register: managed
  delegate_to: localhost

- name: Set managed_files to list of managed provisioning files
  ansible.builtin.set_fact:
    managed_files: "{{ managed.files | map(attribute='path') | map('regex_replace', '^.*/provisioning/', '') | sort | list }}"
  delegate_to: localhost

- name: Get list of installed provisioning files
  ansible.builtin.find:
    path: /srv/monitoring/grafana/provisioning
    recurse: true
  register: remote_files

- name: Set remote_files to list of provisioning files in remote
  ansible.builtin.set_fact:
    remote_files: "{{ remote_files.files | map(attribute='path') | map('regex_replace', '^.*/provisioning/', '') | sort | list }}"

- name: Remove provisioning files in Remote that are not Managed
  ansible.builtin.file:
    path: /srv/monitoring/grafana/provisioning/{{ provisioning_file }}
    state: absent
  loop: "{{ remote_files | difference(managed_files) }}"
  loop_control:
    loop_var: provisioning_file

- name: Copy Grafana provisioning directory to /srv/grafana
  ansible.builtin.copy:
    owner: root
    group: root
    mode: '0644'
    dest: /srv/monitoring/grafana/provisioning
    src: grafana/provisioning/
