---
- name: Create docker-compose directory for monitoring
  ansible.builtin.file:
    owner: root
    group: root
    mode: '0755'
    state: directory
    path: /srv/monitoring

- name: Copy docker-compose files to /srv/monitoring
  ansible.builtin.copy:
    owner: root
    group: root
    mode: '0644'
    dest: /srv/monitoring/
    src: docker-compose.yml

- name: Include pre-activation tasks
  block:
    - name: Include prometheus pre-activation tasks
      ansible.builtin.import_tasks: prometheus-pre.yaml
    - name: Include grafana pre-activation tasks
      ansible.builtin.import_tasks: grafana-pre.yaml

- name: Enable monitoring docker
  community.docker.docker_compose_v2:
    project_src: /srv/monitoring
    wait: true
    wait_timeout: 90

- name: Include post-activation tasks
  block:
    - name: Include prometheus post-activation tasks
      ansible.builtin.import_tasks: prometheus-post.yaml
    - name: Include grafana post-activation tasks
      ansible.builtin.import_tasks: grafana-post.yaml
