---
# podman/tasks/main.yaml

- name: Install Podman
  ansible.builtin.apt:
    name: podman
    state: present
    update_cache: true
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Install uidmap for UserNS support
  ansible.builtin.apt:
    name: uidmap
    state: present
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Create 'containers' user for UserNS auto mapping
  ansible.builtin.user:
    name: containers
    system: true
    shell: /usr/sbin/nologin
    create_home: false

- name: Allocate massive subuid range for containers user
  ansible.builtin.lineinfile:
    path: /etc/subuid
    regexp: '^containers:'
    line: 'containers:1000000:1073741824'
    create: true
    mode: "0644"

- name: Allocate massive subgid range for containers user
  ansible.builtin.lineinfile:
    path: /etc/subgid
    regexp: '^containers:'
    line: 'containers:1000000:1073741824'
    create: true
    mode: "0644"

- name: Create podman-system-prune service
  ansible.builtin.copy:
    owner: root
    group: root
    mode: "0644"
    dest: /etc/systemd/system/podman-system-prune.service
    content: |
      [Unit]
      Description=Run Podman system prune

      [Service]
      Type=oneshot
      ExecStart=/usr/bin/podman system prune -af

- name: Create podman-system-prune timer
  ansible.builtin.copy:
    owner: root
    group: root
    mode: "0644"
    dest: /etc/systemd/system/podman-system-prune.timer
    content: |
      [Unit]
      Description=Run Podman system prune daily

      [Timer]
      OnCalendar=daily
      Persistent=true

      [Install]
      WantedBy=timers.target

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable podman-system-prune timer
  ansible.builtin.systemd:
    name: podman-system-prune.timer
    enabled: true
    state: started

- name: Enable Podman Auto-Update Timer
  ansible.builtin.systemd:
    name: podman-auto-update.timer
    enabled: true
    state: started
