# Tailscale OAuth secret to register tailscale devices with
# different tags, see the 'Tailscale OAuth' section in the
# README for more information.
tailscale_oauth_secret: ""

# Auth key used by tsidp to register itself, everything from
# tag:container and user devices should have access to it to
# allow for OAuth2 authentication.
tsidp_tskey: ""

# Hostname of the Hetzner StorageBox
borgmatic_ssh_hostname: ""
# Username to access the Hetzner StorageBox
borgmatic_ssh_username: ""
# Password to access the Hetzner StorageBox
borgmatic_ssh_password: ""
# Passphrase for Borgmatic to backup
borgmatic_repository_passphrase: ""
# Webhook URL to send notifications on Discord
borgmatic_discord_hook: ""

# API Key to auth to Crowdsec with Caddy
caddy_crowdsec_api_key: ""
# List of IPs which are to be trusted by Crowdsec
crowdsec_trusted_ips: []
# API Key to crowdsec firewall bouncer
caddy_cs_firewall_bouncer_key: ""

# Webhook URL to send notifications on Discord
netdata_discord_alarm_webhook_url: ""

# Token provided by the Forgejo to register runners
# can be shared across all runners and we --name them
# differently based on the inventory hostname
forgejo_runner_token: ""

# ansible/vars/settings.yaml (Append to the bottom)
# Password for the ArchiSteamFarm Web UI (IPC)
asf_ipc_password: ""

# These are URLs for heartbeats to be sent to HetrixTools, they are used to monitor the uptime of the services
# that are not exposed to the public internet and thus cannot be monitored by external services.
heartbeat_keep_vm_alive: ""
heartbeat_syncthing: ""
heartbeat_netdata: ""
