apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: asf-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: asf
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: pomerium
        - ipBlock:
            cidr: 10.42.0.0/16
        - ipBlock:
            cidr: fd42:10:42::/56
      ports:
        - port: http
          protocol: TCP
