---
- name: Ensure Quadlet directory exists
  ansible.builtin.file:
    path: /etc/containers/systemd
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Store tsidp Tailscale Auth-Key as a Podman Secret
  containers.podman.podman_secret:
    name: tsidp_ts_key
    state: present
    data: "{{ tsidp_tskey }}"
    # We will replace with this in the future but currently we are held back by
    # a regression: https://github.com/tailscale/tsidp/issues/159
    # data: "{{ tailscale_oauth_secret }}?ephemeral=false"
    force: true

- name: Deploy tsidp Quadlets
  ansible.builtin.template:
    owner: root
    group: root
    mode: "0644"
    dest: "/etc/containers/systemd/{{ item | regex_replace('\\.j2$', '') }}"
    src: "{{ item }}"
  loop:
    - tsidp.network.j2
    - tsidp-data.volume
    - tsidp.container.j2
  notify: Restart tsidp

- name: Ensure tsidp service is enabled and started
  ansible.builtin.systemd:
    daemon_reload: true
    name: tsidp.service
    state: started
    enabled: true
