apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-mashu-maxice8-com
  namespace: gateway-system
spec:
  secretName: wildcard-mashu-maxice8-com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
  dnsNames:
    - mashu.maxice8.com
    - "*.mashu.maxice8.com"
    - rancher.maxice8.com
    - id.maxice8.com
    - pomerium.maxice8.com
    - netbird.maxice8.com
