---
- name: Fail if ghost_domain_name is empty
  delegate_to: localhost
  ansible.builtin.fail:
    msg: The variable 'ghost_domain_name' needs to be a non-empty value
  when: ghost_domain_name == ""

- name: Fail if ghost_email_user is empty
  delegate_to: localhost
  ansible.builtin.fail:
    msg: The variable 'ghost_email_user' needs to be a non-empty value
  when: ghost_email_user == ""

- name: Fail if ghost_email_pass is empty
  delegate_to: localhost
  ansible.builtin.fail:
    msg: The variable 'ghost_email_pass' needs to be a non-empty value
  when: ghost_email_pass == ""

- name: Ensure Ghost config directory exists
  ansible.builtin.file:
    path: /etc/ghost
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create Ghost EnvironmentFile
  ansible.builtin.template:
    src: ghost.env.j2
    dest: /etc/ghost/ghost.env
    owner: root
    group: root
    mode: "0600"
  notify: Restart Ghost

- name: Create Ghost SMTP Podman Secret
  containers.podman.podman_secret:
    name: ghost_smtp_password
    state: present
    data: "{{ ghost_email_pass }}"
    force: true

- name: Ensure Quadlet directory exists
  ansible.builtin.file:
    path: /etc/containers/systemd
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy Ghost Quadlets
  ansible.builtin.template:
    owner: root
    group: root
    # Keeping your secure 0600 permissions since this contains SMTP passwords
    mode: "0600"
    dest: "/etc/containers/systemd/{{ item | regex_replace('\\.j2$', '') }}"
    src: "{{ item }}"
  loop:
    - ghost-data.volume
    - ghost.container.j2
  notify: Restart Ghost

- name: Ensure Ghost service is started
  ansible.builtin.systemd:
    daemon_reload: true
    name: ghost.service
    state: started
