---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Apply borgmatic tmpfiles
  ansible.builtin.command: systemd-tmpfiles --create /etc/tmpfiles.d/borgmatic.conf
  changed_when: true

- name: Rebuild borgmatic container
  ansible.builtin.systemd:
    name: borgmatic-build.service
    state: restarted

- name: Restart borgmatic timer
  ansible.builtin.systemd:
    name: borgmatic.timer
    state: restarted
