---
- name: Create docker-compose directory for gitea
  ansible.builtin.file:
    owner: root
    group: root
    mode: '0755'
    state: directory
    path: /srv/gitea

- name: Copy files to /srv/gitea
  ansible.builtin.copy:
    owner: root
    group: root
    mode: '0644'
    dest: /srv/gitea
    # TODO: if we have other files this might change, so keep an eye out
    src: ./

- name: Enable gitea docker
  community.docker.docker_compose_v2:
    project_src: /srv/gitea
