---
- name: Create docker-compose directory for gitea
  ansible.builtin.file:
    owner: root
    group: root
    mode: '0755'
    state: directory
    path: /srv/gitea

- name: Copy docker-compose files to /srv/gitea
  ansible.builtin.copy:
    owner: root
    group: root
    mode: '0644'
    dest: /srv/gitea/
    src: docker-compose.yml

- name: Enable gitea docker
  community.docker.docker_compose_v2:
    project_src: /srv/gitea
