---
- name: Fail if gitea_tsclient_key is not filled
  ansible.builtin.fail:
    msg: "Please set the variable 'gitea_tsclient_key' in settings.local.yaml"
  when: gitea_tsclient_key == ""

- name: Create docker-compose directory for gitea
  ansible.builtin.file:
    owner: root
    group: root
    mode: '0755'
    state: directory
    path: /srv/gitea

- name: Copy docker-compose files to /srv/gitea
  ansible.builtin.template:
    owner: root
    group: root
    mode: '0644'
    dest: /srv/gitea/docker-compose.yml
    src: docker-compose.yml.j2
  notify: Restart Gitea

- name: Copy configuration files to /srv/gitea/config
  ansible.builtin.copy:
    owner: root
    group: root
    mode: '0755'
    dest: /srv/gitea/
    src: config

- name: Enable gitea docker
  community.docker.docker_compose_v2:
    project_src: /srv/gitea
    wait: true
    wait_timeout: 30
