services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
      # /metrics
      - "2020:2020"
    labels:
      # Have caddy listen on :2020 and reverse proxy to itself in :2019 to get /metrics
      - caddy_1=:2020
      - caddy_1.handle=/metrics
      - caddy_1.handle.reverse_proxy=localhost:2019
      - caddy_1.handle.reverse_proxy.header_up=Host localhost:2019
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    networks:
      - caddy_network
  
  whoami:
    image: traefik/whoami
    labels:
      caddy: whoami.maxice8.com
      caddy.reverse_proxy: "{{upstreams 80}}"
    restart: always
    networks:
      - caddy_network

networks:
  caddy_network:
    name: caddy_network
    driver: bridge

volumes:
  caddy_data: