services:
  server:
    image: codeberg.org/forgejo/forgejo:9
    container_name: forgejo
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__service__DISABLE_REGISTRATION=true
      - FORGEJO__service_0x2E__REQUIRE_SIGNIN_VIEW=false
      - FORGEJO__service__REQUIRE_SIGNIN_VIEW=false
    volumes:
      - ./forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '30002:3000'