---
- name: Fail if borgmatic_ssh_hostname is empty
  delegate_to: localhost
  ansible.builtin.fail:
    msg: The variable 'borgmatic_ssh_hostname' needs to be a non-empty value
  when: borgmatic_ssh_hostname == ""

- name: Fail if borgmatic_ssh_username is empty
  delegate_to: localhost
  ansible.builtin.fail:
    msg: The variable 'borgmatic_ssh_username' needs to be a non-empty value
  when: borgmatic_ssh_username == ""

- name: Fail if borgmatic_ssh_password is empty
  delegate_to: localhost
  ansible.builtin.fail:
    msg: The variable 'borgmatic_ssh_password' needs to be a non-empty value
  when: borgmatic_ssh_password == ""

- name: Install sshpass and apprise
  ansible.builtin.apt:
    name:
      - borgmatic
      - apprise # Just to be sure
    state: present
    update_cache: true

- name: Generate backup-rsync SSH key
  community.crypto.openssh_keypair:
    path: /root/.ssh/borgbackup
    type: ed25519
    size: 4096
    passphrase: ""
    owner: root
    mode: "0600"
    comment: "root@{{ inventory_hostname }}"

- name: Install SSH key
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail; \
      cat /root/.ssh/borgbackup.pub | \
      sshpass -p '{{ borgmatic_ssh_password }}' \
      ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -p 23 \
      '{{ borgmatic_ssh_username }}@{{ borgmatic_ssh_hostname }}' \
      install-ssh-key
  register: install_key_output
  changed_when: "not 'is already configured' in install_key_output.stdout"

# Ubuntu has 1.4.3 which is an old version (very bad!), and only 1.7.x has
# proper (bugless) support for --global which install to /usr/local/bin
# but no problem (so far) as the systemd service uses /root/.local/bin
# TODO: fix this when we upgrade Ubuntu
- name: Install borgmatic pipx via pipx
  community.general.pipx:
    name: borgmatic
    # Use source as this value is passed as-is
    source: borgmatic[Apprise]
    # Install+Upgrade
    state: latest
    # Use the proper version
    executable: /usr/local/bin/pipx
    # Install globally
    global: true

- name: Create configuration directory
  ansible.builtin.file:
    owner: root
    group: root
    mode: "0755"
    state: directory
    dest: /etc/borgmatic

- name: Install configuration from template
  ansible.builtin.template:
    owner: root
    group: root
    mode: "0600"
    dest: /etc/borgmatic/config.yaml
    src: config.yaml.j2

- name: Create borgmatic systemd service
  ansible.builtin.copy:
    owner: root
    group: root
    mode: "0644"
    dest: /etc/systemd/system/borgmatic.service
    src: borgmatic.service

- name: Create borgmatic systemd timer
  ansible.builtin.copy:
    owner: root
    group: root
    mode: "0644"
    dest: /etc/systemd/system/borgmatic.timer
    src: borgmatic.timer

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable borgmatic timer
  ansible.builtin.systemd:
    name: borgmatic.timer
    state: started
    enabled: true
