---
- name: Ensure Pomerium config directory exists
  ansible.builtin.file:
    path: /etc/pomerium
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Store Pomerium Secrets as Podman Secrets
  containers.podman.podman_secret:
    name: "{{ item.name }}"
    state: present
    data: "{{ item.data }}"
    force: true
  loop:
    - { name: 'pomerium_client_secret', data: '{{ pomerium_client_secret }}' }
    - { name: 'pomerium_cookie_secret', data: '{{ pomerium_cookie_secret }}' }
  when: item.data != ""

- name: Template Pomerium route configuration
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/pomerium/config.yaml
    owner: root
    group: root
    mode: "0600"
  notify: Restart Pomerium

- name: Ensure Quadlet directory exists
  ansible.builtin.file:
    path: /etc/containers/systemd
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy Pomerium Quadlet
  ansible.builtin.template:
    owner: root
    group: root
    mode: "0644"
    dest: /etc/containers/systemd/pomerium.container
    src: pomerium.container.j2
  notify:
    - Reload systemd
    - Restart Pomerium

- name: Ensure Pomerium service is started and enabled
  ansible.builtin.systemd:
    daemon_reload: true
    name: pomerium.service
    state: started
    enabled: true
