apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: forgejo-runner-credentials
spec:
    secretTemplates:
        - name: forgejo-runner-credentials
          stringData:
            FORGEJO_RUNNER_TOKEN: ENC[AES256_GCM,data:pdeBUyPhcKDh8Qi7A8d03xzO1bCoEJ9OcOU6Fe9OUVWmSMdKC1SW+A==,iv:TquN+vzl0SxXer8Hg4ZS2s0NieYpJcL32txzBsBczA0=,tag:UjDz9lkKwqEH692c1tMzzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbXZSZFd6ZFVYb3k1b2Vv
            Q2FzZ2t5OEtSS2xkUllIdWQ0MGxUNy9nREIwCkFpUUovV1BwdUtoUEhPbzVJZ2VK
            TmZNaHBmZklMbEQvSktFT1lBSllrMWMKLS0tIFVIYXFCS1JvQjJDQldGaVltNlFi
            S0theFU2K1AvdElJcUlpSXJZUmorKzgK79lIIcn+CUUzBAfVj2Vb9Rwyo3AaS4x/
            zBk6L1B0wyZGms3s7Z/bNBZv7VJYS1bXAKMHKxwBgLSaLHcHxYQzMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dcdy9jdwvq6nrsxdtvgs05fuyd9fgfx3x788aky3zcsfc6kmhajqt0d86w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T00:57:43Z"
    mac: ENC[AES256_GCM,data:0Dp8IkDv9KfAXJwUequNuwFVNPsTjNsB0LK/6ryiRTHS49bPcFD40KbpE5IHyDGQVbM1CH5HeO5ZXBU8VkUbCQIyPTUpO0FwMzpgfx5+nQGlthpNbi7TYsb/pBCfJbPy43UORwMpMgy7az59oTFATgQamNSq8fXhq+9V1scBsgY=,iv:BejVUrUDjty8jm73cNbqA9ExX53sPNwY0nnmpm76jhk=,tag:jiedukZtSz2VICyv5+OT8w==,type:str]
    version: 3.13.3
