apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - credentials.sops.yaml
  - forgejo-deployment.yaml
  - forgejo-persistent-volume-claim.yaml
  - forgejo-service.yaml
  - network-policy.yaml
  - route.yaml
  - runner-deployment.yaml
  - runner-persistent-volume-claim.yaml

configMapGenerator:
  - name: forgejo-runner-config
    files:
      - config.yml
      - daemon.json
      - entrypoint.sh
