apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner-config
data:
  config.yml: |
    log:
      level: info

    runner:
      file: .runner
      name: "mashu-runner"
      capacity: 1
      envs:
      timeout: 3h
      shutdown_timeout: 3h
      fetch_interval: 2s
      labels:
        - "alpine:docker://alpine:latest"
        - "docker:docker://docker:dind"
        - "ubuntu-latest:docker://node:20-bookworm"

    cache:
      enabled: true
      dir: ""

    container:
      network: ""
      enable_ipv6: true
      privileged: false
      options:
      workdir_parent:
      valid_volumes:
        - '**'
      docker_host: ""
      force_pull: false

    host:
      workdir_parent:
  daemon.json: |
    {
      "ipv6": true,
      "experimental": true,
      "ip6tables": true,
      "fixed-cidr-v6": "fd7a:115c:a1e0:1::/64",
      "default-address-pools": [
        {
          "base": "172.30.0.0/16",
          "size": 24
        },
        {
          "base": "fd7a:115c:a1e0:100::/56",
          "size": 64
        }
      ]
    }
  entrypoint.sh: |
    #!/bin/sh
    set -eu
    cd /data

    until nc -z 127.0.0.1 2375; do
      sleep 1
    done

    if [ ! -f .runner ]; then
      forgejo-runner register --no-interactive \
        --instance "$FORGEJO_INSTANCE_URL" \
        --token "$FORGEJO_RUNNER_TOKEN" \
        --name "forgejo-runner-mashu"
    fi

    exec forgejo-runner daemon --config /etc/forgejo-runner/config.yml
