apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argus-credentials
spec:
    secretTemplates:
        - name: argus-credentials
          stringData:
            GITHUB_TOKEN: ENC[AES256_GCM,data:kiMaMB0cRAFr+wLWDk33iRwFIeRl8ReozWLQZo1BkaWBDghhz7vI0e5+Wvz8/ozPGNoHqUJ99hFR5s73Elu27oP86fcYOkU1niOFi/DBppN+CATRtwqg9nKY0d7i,iv:zAKODeTZBYFSskPbachMeNMMjNicHdiK7s2eTvQ9DgU=,tag:BkJFvM7GkNwj7OfjUp97UA==,type:str]
            DISCORD_WEBHOOK_ID: ENC[AES256_GCM,data:msoujoi911py3OYvHadB7PVgkQ==,iv:lg66K7I5/innuAyr8p9eONtK4gG2c3W4y9MDKBjnA/s=,tag:UmeNwSBr9Y+l86u6slEgfQ==,type:str]
            DISCORD_TOKEN: ENC[AES256_GCM,data:mm3wC5DYEjPOGcO46tnCu6gkZ4NzAL8LXCqMCPdcvB8yOJg7NO5YdzijwpB4YWrF5P4b4gCY1HcuAcYRir2/G/7FUlM=,iv:h499Be+isSUOUXyUZQAyPwYpD9A5n4oT0i5nvIWCm3o=,tag:ByUvN0l1drMFxcokbVuenA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUjd5U256U1JBT29COGt2
            bENjVEJZb3prYjNRR1RBNnhrRVRmSTVjWVVzCkZqT3htRjM4cWZxRkJOVTRNT25k
            MWtWdkpkR1N1TkhYYkxqZlZQUzlScmMKLS0tIG1aUlV4RjFFZmNieVEvRkg5L2NZ
            ejNHdGtsWkE3dXhaS2dNZnZYd3laM3MK9ckf8ZPapII7FY2+A9h0zFDgU5jjJGnH
            x5fFt9kzDo5GLnZEZcx6XkYEd+QxAHywfz4J4buUoCo3zh/82cLF0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dcdy9jdwvq6nrsxdtvgs05fuyd9fgfx3x788aky3zcsfc6kmhajqt0d86w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T01:46:40Z"
    mac: ENC[AES256_GCM,data:7ew27uKVe3Ug61utvw/CgxZa0papF4YA6LxAV1SGYzKZ9SirIFBrZkF0FeWCxOfSDpucTDyDf1P5iUx9xTYww94ExeVur5UDuuzP4hxoE1w9CV3RAIeDg4JTbw7WgmWhlE6d3zY+N7x8OvQt7srUzObwZ4d7hC/qByNAZLy7M7M=,iv:AEVGpvaL1tZZLlUNcEySWXnbg7CtS5ZZhWfA5yMat+s=,tag:mps8vziUjjFI7Q20VzVQwQ==,type:str]
    version: 3.13.3
