apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argus-credentials
spec:
    secretTemplates:
        - name: argus-credentials
          stringData:
            GITHUB_TOKEN: ENC[AES256_GCM,data:kiMaMB0cRAFr+wLWDk33iRwFIeRl8ReozWLQZo1BkaWBDghhz7vI0e5+Wvz8/ozPGNoHqUJ99hFR5s73Elu27oP86fcYOkU1niOFi/DBppN+CATRtwqg9nKY0d7i,iv:zAKODeTZBYFSskPbachMeNMMjNicHdiK7s2eTvQ9DgU=,tag:BkJFvM7GkNwj7OfjUp97UA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUjd5U256U1JBT29COGt2
            bENjVEJZb3prYjNRR1RBNnhrRVRmSTVjWVVzCkZqT3htRjM4cWZxRkJOVTRNT25k
            MWtWdkpkR1N1TkhYYkxqZlZQUzlScmMKLS0tIG1aUlV4RjFFZmNieVEvRkg5L2NZ
            ejNHdGtsWkE3dXhaS2dNZnZYd3laM3MK9ckf8ZPapII7FY2+A9h0zFDgU5jjJGnH
            x5fFt9kzDo5GLnZEZcx6XkYEd+QxAHywfz4J4buUoCo3zh/82cLF0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dcdy9jdwvq6nrsxdtvgs05fuyd9fgfx3x788aky3zcsfc6kmhajqt0d86w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T09:38:56Z"
    mac: ENC[AES256_GCM,data:oOp7/+cyDt+FAOzOHI9OgT0O/Auk9fREEqXndkViR4a4yPPvtagU2LZzwR4QEirN5Z8GNaa7ymq5pxl1kRuUsVVZ8gFHT36mRpWGkwG1clEH82RIqRkoXk3h9OTLNUtM3i6oLCdzt16yPp9eZfiJCdEz4EtT4AIqI/4ybpHfjEM=,iv:0WLHhpvV72np0lsbRL+PTe2RJBXSU9uRVCm4qBWvxZs=,tag:Ds+ag6KXNnUcMhXOrnVPBw==,type:str]
    version: 3.13.3
