---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart DinD
  ansible.builtin.systemd:
    name: dind.service
    state: restarted

- name: Restart Forgejo Runner
  ansible.builtin.systemd:
    name: runner.service
    state: restarted
