---
- name: Create docker-compose directory for prometheus
  ansible.builtin.file:
    owner: root
    group: root
    mode: '0755'
    state: directory
    path: /srv/prometheus

- name: Copy docker-compose files to /srv/prometheus
  ansible.builtin.copy:
    owner: root
    group: root
    mode: '0644'
    dest: /srv/prometheus/
    src: docker-compose.yml

- name: Copy custom Prometheus config using Jinja templating
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /srv/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'

- name: Create prometheus rules directory
  ansible.builtin.file:
    owner: root
    group: root
    mode: "0755"
    path: /srv/prometheus/rules
    state: directory

- name: Add node-exporter alerts for prometheus
  ansible.builtin.get_url:
    owner: root
    group: root
    mode: '0644'
    url: https://raw.githubusercontent.com/samber/awesome-prometheus-alerts/master/dist/rules/host-and-hardware/node-exporter.yml
    dest: /srv/prometheus/rules/node-exporter-rules.yml

- name: Enable prometheus docker
  community.docker.docker_compose_v2:
    project_src: /srv/prometheus
