---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Tailscale
  ansible.builtin.systemd:
    name: ts-asf.service
    state: restarted

- name: Restart ASF
  ansible.builtin.systemd:
    name: asf.service
    state: restarted
