apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: netbird-credentials
spec:
    secretTemplates:
        - name: netbird-server-config
          stringData:
            config.yaml: ENC[AES256_GCM,data:KjxXcbphsI5wqRipaw4VuKHPsbbCfC3FpYtyOiCStrkx9ibjbfumjNr9VOCdh54Uq9TjkC7337UsciTIWS1ONlhbGPu4lqp48ckx/NY9p+uR90YtLBNkh4PJsNoNEMF5FYeGOKS00caMhc53LlwGkirF0iIG8zd0xTJr1BsB3FnG2qQDuuYRYhUmXilhRArjoaDh791ZBCyi1KMu0EvO4ifCOdPgSQ7WCsZFZAqVp1k0dKckRm+XMJLpkfMpIFdEDEKHL/68dcN4VF7uVnbPmmfUhziL8dHKOpFr1qsAlT7s2OfvrzkKVvsrM0g79Lt/47CM6cO8ktFx2E28pGnzXWSpC+73/RUDTJOn5PQqEQWCrk4c/vMQWyFdPRphU7d7Wf/5eOQEztiSUNuadqsCCA28nGYnSdsVu0IR5arVP53/zHWb1p3ERkSEaV/yLsK4yEkqR9G0m/04aGmYmUax5LD7sCt2mnYHOT7xroBfNSSENR239CXFGowVCZzaUv99Z9ARQjkzk/fOS/nO7R/BmYeWzPPWBbHdOObDjalld7FV6gHcvgQkMH5oZkWyqE90eeCasLFOHeeu7vWIsG3F47jqJI2PnBSVo5o19sV5wR6nNGs2CYEf7F2tDdpNK57yZ3RWIUw+N0rQL3cnbEL9J8LWeMBS/evpIJIQArzRSo4tpDaCLjqw3eovpEDs6p99N/Ip/gsGu6nzW0QpEW6JQweMFKCJ+pSgb3U4J1xkLRTAe6TPz2sDUV1PUBpYHaJHercro1/Kb27MjGb1BJTX+RbiNCjoAmD2nmBv62qElbLsNPEb6mw812Z26qi4xRBwRkXYln2TkbsFkzofSuS440Kq3u9ZV/7jrQ7t8ocBpbJnTxDWQEl+kd3fxJXra4AgHcKjLHZVRWgMspmYJc6Aza+jQW2PO8nlTkwhVRtlECdBe4Ia+y0w0zDdJ4ShMI/xK9AQ2onHhY09o0olWLONzlLdZ29zoWx7p/uL/qgU/wtxLZ+FsQzda0QOLi4zJ0fDyOswTwHi5czBPAYRQksrbP8IxqAg5q5SCMfzLGRztPZJeI2zW4kJXYPkdv9R+WMsx1VGLl+yKncEtTgSjAYNtPZShIcLCEeTAlGOuhLo8+jsKiASkwwzDsqblrZJnmBzWRqmClkUq6WiH3kUe2GF1VSWJVoP6lga2YhHQy3vj3umgco77ahxhl0pplbq4pQyCftfQFuK0FXJ,iv:D+M9o8JA6ZLIBIDvbKYBJM8rqF9gRL40oMMI83NoQEs=,tag:3EyWcmpehGAJkIXxk/JCqw==,type:str]
        - name: netbird-dashboard-credentials
          stringData:
            AUTH_AUTHORITY: ENC[AES256_GCM,data:PSAeJEyQwUGOFuLvEQ6Bm2h2vvVq1DszHqVNf06ylwp30A==,iv:VykXIGL1l8FK6F/ApnWpljt+SC8ACx8HKEgTYOywlOQ=,tag:3eXzz5QoIH3E/sZSzPGnGA==,type:str]
            AUTH_CLIENT_ID: ENC[AES256_GCM,data:6ogMrGBliMjlP5xHBtd9Ork=,iv:tkk4itAUJzo78nYlK0F8fDrWwiKYCeJUuiNc51/RF2k=,tag:mszanr2SXinL5ptfDj9EUg==,type:str]
            NGINX_SSL_PORT: ENC[AES256_GCM,data:H8xu,iv:c1LMkXuiKc6yh6hDHVjbrW38XGgz9yYdPLYKPWlnQHU=,tag:ksAay4Tlf53iSwWiDibXmg==,type:str]
            NETBIRD_MGMT_API_ENDPOINT: ENC[AES256_GCM,data:RGzAhFGCx4g78xOnOAeTT2gi+l/jg0SV3alY,iv:gxwMug/SRb5FieHrMLQOX7KjSaC1IqnIt7hPDadoK7k=,tag:LgLUuVFSEZ3JvQV1MfOVUQ==,type:str]
            NETBIRD_MGMT_GRPC_API_ENDPOINT: ENC[AES256_GCM,data:aFOCt7PnfVXjuP4/axAHMlGJdG5lUwNxV4tr,iv:pd0mWRha6bN9UiQzPwhlzO5yIPF8YF67ht4xXFSPnn8=,tag:f6aeeRecYl8eEFfk+3K1Dw==,type:str]
            AUTH_CLIENT_SECRET: ""
            AUTH_REDIRECT_URI: ENC[AES256_GCM,data:19Llgqqxrg8=,iv:nAQGqloFIauQy2zNj8e7Sx46krItFUipk2U3FHeKqRo=,tag:/pDf+KxjS8rjIYh2wfLAow==,type:str]
            AUTH_AUDIENCE: ENC[AES256_GCM,data:G7a6h8WpoHFeoh9tGwRhSzk=,iv:pwnhceoiFFR+8ogUM7OwPizitUqgrDXGEV5/OoKNcck=,tag:XMlKCDLOS6LyCY2G3G/Meg==,type:str]
            AUTH_SUPPORTED_SCOPES: ENC[AES256_GCM,data:vUxbWvHEN7up6YzrInbPKN+8j3iwecreQgOL,iv:LRtIZGy3bqaCq93WxlsOHdTqA35TsK4upNkmRzUR+XI=,tag:VopLRG4UfAUBt0L/LEF8Zw==,type:str]
            LETSENCRYPT_DOMAIN: ENC[AES256_GCM,data:MYazbQ==,iv:5skasKZgNNQQgN/Juxa7d90Ra/YSa2d9PAWyjDle7MU=,tag:2KeMEXI+OFtv5kt0QY2ksA==,type:str]
            AUTH_SILENT_REDIRECT_URI: ENC[AES256_GCM,data:cSlT6q4nXQxmC9Dn1zBP,iv:6GgHSnoZy27ogYY377JH0+PklTb2xorVkVavvHbHM6I=,tag:3IKoJUXggjvq7oU2QA3n4A==,type:str]
            USE_AUTH0: ENC[AES256_GCM,data:DBE6j/c=,iv:USspytwOYZfVnfhZ+/fXnvPb9f0Mh03tSh7YXAq4bkE=,tag:OemhZsZ1kZRarYBM9EQy+w==,type:str]
            PATH: ENC[AES256_GCM,data:Aph91zI4tT5N8s0LCG70TMDrK7cG3nMaLtCghmesnOXXIuACpkIeisJH74GTJstwmw9hxjh5cRHjaeFE,iv:9E3lEYEfuyigsofajytFXMDAUebOLdXTlYlKnStGpAA=,tag:V8BI1n3c7mwxLlK2QyrqYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZFd0bWJobUh1cTRWcnJP
            UDg0anIvd04zM3JON1Zkb1ZpSkd4QkV2QlNrCkJ0N3A2M29KRkgxR3pPNUg5QTNh
            b1orSW1ndFM0ZlpObDNuVEVaam9XdGMKLS0tIFdhVFBqQUlDMzBhVUJ2L1plZStm
            WU9BQTRyU1dndFpaNXozajg1SFQyQzgKUdWF/r2vkkpNc7PpnfHCszF8Go2iEMdk
            rLrLKuETlBp6PWbLJoelPjfmktzF2ITvVSPkZr/Y9J3auHx313Iu+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dcdy9jdwvq6nrsxdtvgs05fuyd9fgfx3x788aky3zcsfc6kmhajqt0d86w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T23:33:29Z"
    mac: ENC[AES256_GCM,data:lajGbjblQymsQlGIIsvik72RUsECuU2jt02WkXSsf0eZOViK9EV7TL2V3r1GO569HVVho0ZFiE+afOQ55BY88NKV8A0SDfTC2OaHxK5ZUaM2RnWfOVzsEVV61TkQZ6XsSC9JIYCLL7P4emtfcs4Pl5ntw2YlcsVvWGoPED1DHhk=,iv:XTNvFi7VTEnVwq9yQEhwVGLaT2sbLTpdH+xP78kcpxw=,tag:lJPB1RGb0wHyS8g3nMBjkg==,type:str]
    version: 3.13.3
