apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: netbird-credentials
spec:
    secretTemplates:
        - name: netbird-server-config
          stringData:
            config.yaml: ENC[AES256_GCM,data:9dlSFmY0o0ATf57gZ3Y5E0tmyQtQWtkGEsim+C7QBPQnIHIK15TUtR9de5zLvz65CfZiy0N1L7azoFqpknm9Y8xQEJ7BwnWYdVjmaVja/Vbv9XlCg/qHqEGBzGEsgqi28Ku06BmsTV+GF5Hjlq0G2HszD7sUzEwA35dZ5dn41Ty9uHTGz0xMiAVnb3j9HujCmhFqTs1VRGFK7hlpvcarZbPWMlhD4I7rTcs0FpBB153NiZsDu06XZSxVCi7XqWUKLx4Kp11u7opegm6O6pZTXJ5hoeAqqxqYTLy6VB5pE6cd7FbdUxvTP0kY7YqCg7S0dJC4zTHHsznBLZycHzSUPSqoq3ZJjNyxX5RST4RQ/NH2XzensCsuSMLj7+hzjGPFAVEZUtJkTVt/JaSDHhdg0u0Q1UDiSmjOJMWdCsliCZtQZth2XpJl4a4S94e4r8hBnCSViLhe8Q3S1qaAq7PW2J5C0wfOAeNqHtO4Yi52bYiXde/B6/4BtdyEwitdZ3zCwiYimEA+oh8IW1j6CqUfsaNQSE/FSy7fzsr6uyjJEwgFRWf47MJiov+t7hKy6AC0gfakp7xpfvevI2dhOoGO5m+1f0avihuS/df7cD2kLFh2W7CnuHeLPeWQsejg2TZRDLA9li5P5qet7/n3RDe01xoDEqURYh4MK8pqU/466MOtPjFINEwTCYFjf0f7fjsOzYj6UZ0IzquPJEsmNviRjVrWlI4NpZal2hDV/Azn918xwZURZMIlN7NlQCgRyukbU4uINKWcztfh2vou8R1FZAvdw1Kxz0YzL615qqpJ1GMfpLLv6WdO+CJg4A0Xd7E6l+8mzzJ5IVBk3u4ZVSwzwd8sBPyT1bMwu1oiTGfAXcAUsU9iAnTSx5IdALgU1Lisxo2BafwWGOKRicjsVhKEVsCoLanikTJeJerQoAyoW5QChBssZXGfxQa2WzPhoZCJ4rY0k9Anl8qRSken5xZPpjD4lZ00rA+67m1Gk90arbH80YYOc7DhRVw7DdAmStHdynuyvou3/hz5sMR+NlzW7PqrCflNi8T2waMK3yLLGJbWSWFIK0opml+nF0kOrsS9KvM6cBI5erVBWgRrAr94S3SoR1rdOXGm7LT47dROOkWCVK8EKuQRb5CSbPLoqKgzBesRqm+X5Wxpf27mX9u+vAI=,iv:HZF9tFlcKKvI6QrM0M3TQa3XJJbjujzjmPRQ2lYUQ5k=,tag:1AOLimVoXoNEOdpiaAaKEw==,type:str]
        - name: netbird-dashboard-credentials
          stringData:
            AUTH_AUTHORITY: ENC[AES256_GCM,data:Zc0/B2fxIG2kKbS5uTuoY01QDQvDtzRDBZ7q5DvHF4Ml0w==,iv:v3r3fGGcDt1dhCaYSxLlbkbkZEGsdnGmoWb4lvT0qqs=,tag:uMbwHPm7pKwpP5CNuRtSpg==,type:str]
            AUTH_CLIENT_ID: ENC[AES256_GCM,data:WzSsfv0SYDp54l5+JIbTCcc=,iv:kwzIxGIkrgTlmWubRzTxqrREmpy+zMMKMdlqIUNOPOk=,tag:Id6EeYeqgZFwgYRz3ELnqA==,type:str]
            NGINX_SSL_PORT: ENC[AES256_GCM,data:cbJ/,iv:EPnH2u90HhfEWiElKR4xXlw079NoUJ5lduRodKMD2jc=,tag:CeOzJTDgn7VH6MJLO7aCLg==,type:str]
            NETBIRD_MGMT_API_ENDPOINT: ENC[AES256_GCM,data:AtwQMujdVkDlb75eq9EbboFni83ZbTIdMw03,iv:hG8a60noMoGavQG9miE6nMMAjDfRxTG9+6i85ZfDurI=,tag:iyY2C9+v/IvQ+tuWJ9GSEg==,type:str]
            NETBIRD_MGMT_GRPC_API_ENDPOINT: ENC[AES256_GCM,data:6oo1hyPqcfUKB+b3HIXKadB1MTcAmNEBZlBX,iv:hoyzlNp7RweVb0fVK+fYXPUGds5MFYpla5evFSgwc/M=,tag:o6igJOQ/qsT+Mn5kuMwkhA==,type:str]
            AUTH_CLIENT_SECRET: ""
            AUTH_REDIRECT_URI: ENC[AES256_GCM,data:YDPjXN2Y0M8=,iv:Tn1EN+aT630svyjHeKwxlzvpE70fWbuyP0Nsr9YG7Ko=,tag:RxLpqTDwPHcvS/QeXDqBzg==,type:str]
            AUTH_AUDIENCE: ENC[AES256_GCM,data:/Y+aRwgz4PTnNfvveIV4YfM=,iv:SpJk1Y1Ged1izu8fMVPphoJ6tdd1YBBGxBOyNFlm1DM=,tag:bFcQFUgJxJ50Kbk8vlcVKA==,type:str]
            AUTH_SUPPORTED_SCOPES: ENC[AES256_GCM,data:2ll3PqCTxqipvB94hNMvfGJKkJj0+d0xhIxE,iv:CbxQDSYUd2yE4qdOopspB0UWakKfnu0Elc2U3T7BsQw=,tag:EDwt3hJgQYww1BzTGQPXmg==,type:str]
            LETSENCRYPT_DOMAIN: ENC[AES256_GCM,data:fc1IlQ==,iv:j61fsfA74lAu/SrDl50eszQSdT7gy6I8GTwRXOOoBrY=,tag:hlad3VgvVDDDlIJZeAHcDA==,type:str]
            AUTH_SILENT_REDIRECT_URI: ENC[AES256_GCM,data:SdyOSr3UuDWJn0oEBNou,iv:lUnaMEXXMzI4UWEZjWoQ+T0QjMat3JwVhLkp10sA4Nc=,tag:/3JZa+FBCTBIkyi4hB5HPw==,type:str]
            USE_AUTH0: ENC[AES256_GCM,data:NodlNJc=,iv:Pt14t1HF5L9yw1HqCS+GmecyImY4aqJ5SagWGN+QNkk=,tag:rMDkCGpWx9oDgJLoDs5k+g==,type:str]
            PATH: ENC[AES256_GCM,data:djnMo2U6KJnVpX2hpeiKSRi7AogPE7PlcZJyoh/UnVQUHZa7o8xGI5ZkwhddsXrAOpTaf91VM+cpj8EW,iv:wPl+/FP6AVqzM1xlaUFaErLHPRvH/DOQ0HrgihM3rTI=,tag:yLBn1waMsBPwo6JttzmeVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VTVHQkZmVU83MGx2ZTlv
            Y05IdUg3YkxQSkR1UG1TQjlRTFhTMWluRkc4Cnk1dFo1QVBvbXBtUTFNSFRKOGZY
            WkkvbkpoZ1ArMncxeE00NEFodXo0UGsKLS0tIFNNYTBXblVCOUx3d3NWVnNKaVdw
            VW14QnRlYW9RUkNNUTh0c1dvc1oxaUkK55facL+eHdtsEK8ChltDWFY/qn8DJq1s
            uh6ucqxQv+BkYk7F4utFx6daJpzLqR26hsN+GlhemPIy21hstbwOWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dcdy9jdwvq6nrsxdtvgs05fuyd9fgfx3x788aky3zcsfc6kmhajqt0d86w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T23:04:24Z"
    mac: ENC[AES256_GCM,data:dZV1zEc9u9xCAAk/fvvAtk+MseeyJwP2CGNR6XKw5ql3duVMnjIoZ0kn4QZW71YGXKU+yV3honVbTUIPfOofX1jH4WVyx3qZKHaqOxE5Dg+WkNj5NGZDNhQHVOKR4vgG1534eZT/mPTCCFHTSr9qG2ZF4WKNHHTKQTFNmlEHbck=,iv:B7s8tfbBtuXkzLaqx3KshI3ahBJcUKS++68AiqteCVA=,tag:er1Ib2LGhNgQWdW8NwSfXA==,type:str]
    version: 3.13.3
