apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: netbird-credentials
spec:
    secretTemplates:
        - name: netbird-server-config
          stringData:
            config.yaml: ENC[AES256_GCM,data:IvRzlhXcNGQjq94IqOTxiPRBS2ZZtWdtyT+nOY+EpWTefOMLoUZ99Q0vddLrdsudonrS3mRUp3tZFnN/ZsKyl/YAqvMGuzKqoNbStM+l8tPD7VSy07vDMmwyCGBPSRevic08WaDUnxArgGXwy46XNm/u4V+fJ0f4Au8rmC6aU0a6UQaMbna1oQsedcEXuxlGV5ffqR2EmUig6RQDc3B0qnBg9pEjf7ZnxLxV3ccrUktyPyf+w6TwYjWZUDXMMPlDiX08wUukKVEO+lLVNMW8iRiFL7matdWBgBkj7tp8E80TzJH23RGuuitbwvJfOv1vCMHyQeFqFx3Uk5VqKJ/T4tnzKxqMd2239GeSzlluD1sSAyHA5vDt/wIMGfpajtxbA3/hflyn1X22IAWtN22rymE8Gnd+jrDgO6F7aIgeJr1OM7X6oHAp3NFY/8aFEck7mOxgZ04UgiQjOwAtKsvJ3cKoZAMU2AVDV/o5sdOhZ73D7IDU9K/CVCi4O7rGQPoVvF2Y3LjjLd3uNg4lEdiPbPKzJun9NQYE8FA8PROMWJxv55+Vcg+UeAqQCzPO/+GYB1DDfi3+gEoHTVbrlaWtvwDM4/vJ80PVhE0MT86RA5lsORNg0SphY/CEbWsIh/CecWYdXaxr0wtnrMc7M+A+f67YImUGSNEY94NC9pcqVi4CPr0igVTB7lYuN/8DtMUJHa/+jg3k4cONa0iKxU4kviihm8lOZwPqz+Wnrz1I0p9Y+Wxz5eEP+ReH5szjG+6cbZYLotJE/kadkUGkXeX+Ftw6O+uXujl3R8xavjV8VChncsn+LCrimUxpi0Xd542KIZ1zs7ec9ePZWZxClQmUQ/n/A0zsdQiXiL9k14n8d4r+hNvP+kXhpWcr26QS9LXXKsFW47O5gJuNhUoYDakjhGUNc1fwSsM4MwJWXPbBI3I54bq7fMOSzlr0jmnHRmdmRIni08BTgrbGdgq+Gzsk7s4Ay/41G/mhdDHob3PJNsLuuemDwDSuoC1KUH6wsyHsw0vnn5CXXjnQCjf0UTspXfJMdYp1n8DH8Dm+x1gdovKf+LYhR0jNNZ8kmtN7XzbEomRkp/ENfGF6HRqXUCbb8pTvUEeQBnrMY42NTuzjmGaeOug62MHhs0jFjdxeRAYLSYAtX41MfombFJU4UcmV4Fllx/YLLvDL5Z2ATb/o5AwIQdUi8gdLZp4CQB5qEk50+mQUUI8gYdw9iaCbxOlkDS8BGg0pv0dhQEtfX27i5keNfiDyerzWKOGcnk4sYoUdderJq25tPfE92gsyqcRk+Im8I8fQTvIFA8Alfg==,iv:1NKnWgVvKFd/UNiy9bPl/wI+qmRf/WB0lZt/QD1SsKA=,tag:24g3CbxsZGnsKW2v4g5ZjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRXF2dy9hNFlJM1U0V1Bz
            N0M5dFZzRVZwMzlnaEVhUnRzOVZhdGR5N0JvCjBJS3JQRG91UzRTWDdKaDZKYUtN
            aUo4WGdJQlF6b3hOb21XYlpHUjFEWVEKLS0tIFVvV0NoZyt1ZENvTDYyTEs2TFN2
            eWd2L0ZZMWRVVDFtUmNpYTlWU3dBVmsKXjQzc4UHsr0srTAFaOMQIGujBPMrmkgx
            wj9Ea2mxe72CCGioLBIU9F+xBgr7ohYxZGZ+wdOc4S24jlcMEQm9mg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dcdy9jdwvq6nrsxdtvgs05fuyd9fgfx3x788aky3zcsfc6kmhajqt0d86w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T01:00:20Z"
    mac: ENC[AES256_GCM,data:Y80OVZQLFJKMzofp1GdNK399ZwnJOhx9d6dXx4q9GbaeVsUj1X6Y4ptLkp4hqEW0V0/hPZCOwaOMMev8fXaGVJ0tHxbFXSqa0E3oeHJyAUkzG+K7bakBmfqR6tMiL2KxXE9jecegqAkzl/AyAL+UKyqI4CL6MvLlogl+dR8v/TU=,iv:igv6mC5WiZrWPdOqv+0GRnfqtZBbKY2KHfzLzeb88Pk=,tag:C9AZ6KZ3FAJhwXbDPikuZw==,type:str]
    version: 3.13.3
