apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - credentials.sops.yaml
  - persistent-volume-claim.yaml
  - deployments.yaml
  - services.yaml
  - route.yaml
