services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    healthcheck:
      test: ["CMD", "/watchtower",  "--health-check"]
      interval: 15s
      timeout: 30s
      retries: 3
