services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '33000:3000'
    networks:
      - net
    volumes:
      - 'grafana-data:/var/lib/grafana'
      - ./grafana/provisioning:/etc/grafana/provisioning
    healthcheck:
      test: "curl -f http://localhost:3000/api/health"
      interval: 15s
      timeout: 30s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '39090:9090'
    networks:
      - net
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules:/etc/prometheus/rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    healthcheck:
      test: wget http://localhost:9090/-/healthy -q -O - | grep -q 'Prometheus Server is Healthy.' || exit 1
      interval: 15s
      timeout: 30s
      retries: 3
  
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    networks:
      - net
    volumes:
      - alertmanager-data:/alertmanager
      - ./prometheus/config.yml:/etc/alertmanager/config.yml
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

volumes:
  grafana-data:
  prometheus-data:
  alertmanager-data:

networks:
  net:
    driver: bridge