# API Key to auth to Crowdsec with Caddy
caddy_crowdsec_api_key: ""
# API Key to crowdsec firewall bouncer
caddy_cs_firewall_bouncer_key: ""

# ansible/vars/settings.yaml (Append to the bottom)
# Password for the ArchiSteamFarm Web UI (IPC)
asf_ipc_password: ""

# These are URLs for heartbeats to be sent to HetrixTools, they are used to monitor the uptime of the services
# that are not exposed to the public internet and thus cannot be monitored by external services.
heartbeat_keep_vm_alive: ""
heartbeat_syncthing: ""
heartbeat_netdata: ""

# Encryption key for Pocket ID, it can be any string but should be kept secret and unique to your deployment
pocket_id_encryption_key: ""
