#ENC[AES256_GCM,data:7U5iMqD/yCfD7JEXJPeja4LlOedYqt9jxq+c4ICVoxftudU+oAg41pWer1x2P0UdY/m796w=,iv:UEfqX1SCZlY4DUdt/kPcndFQ/0hOu9SXducIDIw+bUY=,tag:g9ieR4JlDqdNJEhOOHNPhQ==,type:comment]
caddy_crowdsec_api_key: ENC[AES256_GCM,data:BX2jKa8P8+rF75KZqywSyUXaEd4q6VkXFkcu/j9mpEF8WirXO4fc2MDkuw==,iv:EyMGeNsrffe723sxDWDjFL7EDb6/4v+RBL0SpfwO4zw=,tag:5O0puReSmgvXpVtip/L1BQ==,type:str]
caddy_cs_firewall_bouncer_key: ENC[AES256_GCM,data:86EraLmLP9BFhAeiQZNaqOFV476oO9DedYrtaTDr4cFykLK6xpE7QVVZZQ==,iv:a8h6jjdKFTC35dp9squttwudVIOjD/nOu/m3XP+xezw=,tag:Wg521XHi+hWSRo/BHzMpvQ==,type:str]
asf_ipc_password: ENC[AES256_GCM,data:8aNvNz+bqRvuescrcJwaZX5r3V7LVvnX6kyBu0Rkn4dWRuJ9zg8J9jyLuuM=,iv:LD78YroPUXd1G7WX499V1BdfFIKkFh5MaDKXzTooceA=,tag:v7Vm/gKoCAv4Vgvjv3vzHA==,type:str]
heartbeat_syncthing: ENC[AES256_GCM,data:RwjLB0d0X/J2gZijSiMufP60jeDrxD/6rNmmh4DKzXhRinxTnvTx/jlFyMxOug/OSKnq601eVAfAFuz7cOaWXrQ=,iv:3uMjcnOuQe+Fk/MF05b+fQqzb+lGxvwB9ERFA3tgzL0=,tag:7/uduYStLqUXceEzo9lNzQ==,type:str]
heartbeat_netdata: ENC[AES256_GCM,data:Tl5NeFhZLJR4YhS9E0ga97lyWoAs1qO09XOtNRn0tW+Ekd0cmNX5Dx9pIcutyfVBhvLxh2f3wJfJe4am+GKgreI=,iv:nAEol9+BO2uFIoXqU/d8PVLEwAAdXpfDq57o5tDPRzY=,tag:HJhaKPiuPxNb4Wif49f0AQ==,type:str]
pocket_id_encryption_key: ENC[AES256_GCM,data:HGYXo5QnbHyxUu34zmHJxVcugQG0js2D5niJ8SZFaE2+cGo/VMY8oNKFVLg=,iv:LNjrZrfOwr4cEsbakeFt9UTmgJeBg5CG861xM3yA64w=,tag:ZdNC8CxGakGDcgKm1hp9jg==,type:str]
sops:
    age:
        - recipient: age1dcdy9jdwvq6nrsxdtvgs05fuyd9fgfx3x788aky3zcsfc6kmhajqt0d86w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbDVhMStvYWc4dHlnSFNL
            TlVBQkdGeEtNd0pLOGZzZGxVcTRTa3ovSmtJCldpWlV3V1pseHUxZHF3UGRGTjg2
            WlkrcWJ3Ymk4Q2d4aklLL0RsbVFMNGMKLS0tIGdOcERob2lKb3h1TnZURWpUNkYx
            SXhmdGE5TmI1VmFBTTBmZzVkSlFqQzgKelHnR+Mi29zU4Rfaaued59XIJxJho99i
            0yPYHBTRfYh/BCRXM8t+kf0IKQ+2dbhWqPZnyULkD6WmNkdk40KfpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T00:11:07Z"
    mac: ENC[AES256_GCM,data:fFVnUbWphmKaZZNJYkkP2rFAc0i1iabhgsivqLT2fiYyzemzEkradRglDH5ttg/CAGi5LPS6fDfqalyLMiXZ89eg1+2O/0cAS788ceFNElNChps+Ij6ljOvN9EhMHXGIUMp5KQVxYzWHEc8yS7GkoIJLBCZmiXk8e4G8W1Ab/HU=,iv:5/+MtYCQ5ugQzAvE0vh/KxV6NLeEHbpmPb0UsnycLCY=,tag:lcpnQLnc84o+n/bt7Lfa5Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
