services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - DOMAIN=https://vault.maxice8.com
      - EXPERIMENTAL_CLIENT_FEATURE_FLAGS=fido2-vault-credentials,ssh-key-vault-item,ssh-agent
      - SIGNUPS_ALLOWED=False
      - IP_HEADER=Cf-Connecting-IP
    env_file: "admin_token.env"
    volumes:
      - ./vw-data/:/data/
    ports:
      - '30001:80'