---
- name: Restart Prometheus
  community.docker.docker_compose_v2:
    project_src: /srv/monitoring
    services:
      - prometheus
    state: restarted

- name: Restart Grafana
  community.docker.docker_compose_v2:
    project_src: /srv/monitoring
    services:
      - grafana
    state: restarted

- name: Bring up monitoring
  community.docker.docker_compose_v2:
    project_src: /srv/monitoring

- name: Restart monitoring
  community.docker.docker_compose_v2:
    project_src: /srv/monitoring
    state: absent
  notify:
    - Bring up monitoring

- name: Restart promtail
  community.docker.docker_compose_v2:
    project_src: /srv/monitoring
    services:
      - promtail
    state: restarted
