---
- name: Create docker-compose directory for beszel
  ansible.builtin.file:
    owner: root
    group: root
    mode: "0755"
    state: directory
    path: /srv/beszel

- name: Copy docker-compose files to /srv/beszel
  ansible.builtin.template:
    owner: root
    group: root
    mode: "0644"
    dest: /srv/beszel/docker-compose.yml
    src: docker-compose.yml.j2
  notify: Restart Beszel

- name: Copy configuration files to /srv/beszel/config
  ansible.builtin.copy:
    owner: root
    group: root
    mode: "0755"
    dest: /srv/beszel/
    src: config
  notify: Restart Beszel

- name: Enable beszel docker
  community.docker.docker_compose_v2:
    project_src: /srv/beszel
