---
- name: Reload Prometheus
  # This requires '--web.enable-lifecycle' which is in the docker compose
  ansible.builtin.uri:
    url: http://localhost:9090/-/reload
    method: POST

- name: Restart Prometheus
  community.docker.docker_compose_v2:
    project_src: /srv/prometheus
    state: restarted
